### ISSUE TITLE
is irclogs.laravel.io is under your Control?

### ISSUE THREAD

**Issue by rajlaksh** [Glose/irclogs#2]
is http://irclogs.laravel.io/ is under your Control?

because http://irclogs.laravel.io/ is dead now.

**Comment by arthurdarcet** [comment]
Hello @rajlaksh 

Yes, irclogs.laravel.io is under our control ; but the `laravel.io` domain is not, and apparently the irclogs subdomain was removed from the DNS zone.

@taylorotwell : the DNS entry should point to `94.23.2.137`, could you restore it?

**Comment by rajlaksh** [comment]
Thanks for fast reply.

**Comment by rajlaksh** [comment]
Done. Thanks for Great Work :+1:

**Comment by arthurdarcet** [comment]
Great, thanks for the report

**Comment by rajlaksh** [comment]
Please check last message i attach Screenshot. 

Is Scrollbar is missing or i've that error.

**Comment by arthurdarcet** [comment]
I'm not sure what you mean?
I've just restored the search, the whole thing was a bit buggy during the past 10 min but everything should be back to normal now

**Comment by rajlaksh** [comment]
as you see in screenshot i can't scroll to after date 17th because there is scroll bar.

**Comment by arthurdarcet** [comment]
what about the huge scroll bar right next to the one your mentioning?

Without access to your computer, this is going to be hard to debug ; but if you know some CSS, don't hesitate to submit a pull request :)

**Comment by taylorotwell** [comment]
I don't manage the laravel.io domain.

**Comment by rajlaksh** [comment]
@taylorotwell  it fixed now.

@arthurdarcet that huge scrollbar for page. 2nd Scroll bar has not scrolling. I was talking about i can't scroll menu after 17th date.

**Comment by arthurdarcet** [comment]
fixed by 8ab82b9fb0adf2840bcb37c382a880de190bfae7

**Comment by ghost** [comment]
thanks

**Comment by kavin-90** [comment]
@arthurdarcet irc logs domain is domain please check
