### ISSUE TITLE
Installation problem(s)

### ISSUE THREAD

**Issue by k0nsl** [Glose/irclogs#4]
I'm trying to install `irclogs` on one of my Debian 8 (jessie) boxes but I've run into a problem, when issuing `composer install` I receive the following:

``` bash
root@S1NE23:~/irclogs# composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laravel/framework 4.0.x-dev -> satisfiable by laravel/framework[4.0.x-dev].
    - laravel/framework 4.0.x-dev requires swiftmailer/swiftmailer 5.0.* -> no matching package found.
  Problem 2
    - Installation request for laravel/framework dev-master -> satisfiable by laravel/framework[dev-master].
    - laravel/framework dev-master requires swiftmailer/swiftmailer 5.0.* -> no matching package found.
  Problem 3
    - laravel/framework 4.0.x-dev requires swiftmailer/swiftmailer 5.0.* -> no matching package found.
    - julien-c/mongovel dev-master requires illuminate/container 4.0.x -> satisfiable by laravel/framework[4.0.x-dev].
    - Installation request for julien-c/mongovel dev-master -> satisfiable by julien-c/mongovel[dev-master].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

I'm not sure what I am doing wrong. I've got `php-swiftmailer (5.2.2-1)` installed on the system and every other dependency as well, I think.

Any ideas?

**Comment by arthurdarcet** [comment]
Hello k0nsl,

irclogs is an old project that isn't really supported anymore…
If you really wish to run it, you can try updating the laravel requirement by running `composer require laravel/framework 4.1.11`, but I don't think the PHP will work out of the box after that and there probably are a few things that will need fixing.

If you manage to make everything running again, feel free to submit a pull request here and I will happily merge it.

The live version is still running here : http://irclogs.laravel.io/

Thanks!
Arthur

**Comment by kavin-90** [comment]
it got **`mongodb.DB.connect`** not a function :laughing:  :cry: 

if i use    `logs: mongojs("irclogs",['logs']),` the i got **`config.logs.save`** not a function :cry:
